apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: humble-cluster
  region: ap-northeast-1
nodeGroups:
  - name: humble-node-group
    minSize: 1
    maxSize: 2
    instancesDistribution:
      instanceTypes: ["t2.medium","t3.medium", "t2.large", "t3.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
